### ISSUE TITLE
Pro Swapper Id

### ISSUE THREAD

**Issue by DrxppyStorm** [Pro-Swapper/Plugins-Json#3]
So when i swap skins with pro swapper id i look in my locker and see the same skins so can you help me??????
![HI](https://user-images.githubusercontent.com/88427446/128148748-dc62403b-6d07-460d-b5cc-522b2147cb2c.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/88427446/128149187-7c2db6a1-6258-42f2-99da-23ca0348d6d5.jpg)

**Comment by DrxppyStorm** [comment]
@kyeondiscord will you pls help

**Comment by KyeOnDiscord** [comment]
You may have a duplicate pakchunk0, I recommend reinstalling Fortnite to fix this. (Delete the paks folder and verify so its only 19gb)

**Comment by DrxppyStorm** [comment]
Wait so I have to delete fortnite and reinstall and then delete pak file in the fortnite file and it will be fixed????????

**Comment by KyeOnDiscord** [comment]
Just delete your paks folder and verify Fortnite :)
